/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.ermay12.regex;

public class Regex {

    public Regex(String expression){
        ;
    }

    public boolean someLibraryMethod() {
        return true;
    }
}
